C++ time to solve:  -64.030104637146
C++ time to solve:  -65.36415982246399
Stat time to build:  -7.152557373046875e-07
Stat time to solve:  -673.4449713230133
Clauses 10 took -805.2930195331573
C++ time to solve:  -66.44206142425537
C++ time to solve:  -65.7090003490448
Stat time to build:  -9.5367431640625e-07
Stat time to solve:  -702.5923178195953
Clauses 10 took -1642.7569615840912
Traceback (most recent call last):
  File "testStatistics.py", line 235, in <module>
    main()
  File "testStatistics.py", line 232, in main
    test3()
  File "testStatistics.py", line 150, in test3
    plt.plot(xAxis, BPPSATpi, c='blue')
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/pyplot.py", line 3019, in plot
    return gca().plot(
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1605, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 315, in __call__
    yield from self._plot_args(this, kwargs)
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 501, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (1,) and (2,)
