../BPPSAT/SATS/UF250.1065.100/uf250-01.cnf
250   1065
average flips:  46153.0
total time:  2.026324987411499
Traceback (most recent call last):
  File "testStatistics.py", line 229, in <module>
    main()
  File "testStatistics.py", line 226, in main
    test250()
  File "/home/ccoughlin/Quantum-3SAT /StatVsShoning/StatSATtest.py", line 453, in test250
    plt.savefig(name)
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/pyplot.py", line 966, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/figure.py", line 3005, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2255, in print_figure
    result = print_method(
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1669, in wrapper
    return func(*args, **kwargs)
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    mpl.image.imsave(
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/matplotlib/image.py", line 1616, in imsave
    image.save(fname, **pil_kwargs)
  File "/cm/shared/apps/conda-environments/python38/lib/python3.8/site-packages/PIL/Image.py", line 2169, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'plots2/StatTest/factorio005.png'
